Get-ChildItem -Recurse -Filter *.tsx src | ForEach-Object {
    $c = Get-Content $_.FullName -Raw
    $c = $c -replace 'bg-slate-50 dark:bg-\[\#0A0F18\]', 'bg-[#0A0F18]'
    $c = $c -replace 'bg-slate-50 dark:bg-base', 'bg-base'
    $c = $c -replace 'border-slate-200 dark:border-white/5', 'border-white/5'
    $c = $c -replace 'border-slate-300 dark:border-white/10', 'border-white/10'
    $c = $c -replace 'border-slate-400 dark:border-white/20', 'border-white/20'
    $c = $c -replace 'text-slate-500 dark:text-white/40', 'text-white/40'
    $c = $c -replace 'text-slate-500 dark:text-white/50', 'text-white/50'
    $c = $c -replace 'text-slate-600 dark:text-white/60', 'text-white/60'
    $c = $c -replace 'text-slate-600 dark:text-white/70', 'text-white/70'
    $c = $c -replace 'text-slate-700 dark:text-white/80', 'text-white/80'
    $c = $c -replace 'text-slate-800 dark:text-white/90', 'text-white/90'
    $c = $c -replace 'text-slate-900 dark:text-white ', 'text-white '
    $c = $c -replace 'text-slate-900 dark:text-white"', 'text-white"'
    $c = $c -replace 'bg-slate-200 dark:bg-white/5', 'bg-white/5'
    $c = $c -replace 'bg-slate-300 dark:bg-white/10', 'bg-white/10'
    $c = $c -replace 'bg-slate-100 dark:bg-white/\[0\.02\]', 'bg-white/[0.02]'
    $c = $c -replace 'bg-slate-100 dark:bg-white/\[0\.015\]', 'bg-white/[0.015]'
    $c = $c -replace 'bg-slate-200 dark:bg-white/\[0\.03\]', 'bg-white/[0.03]'
    $c = $c -replace 'hover:bg-slate-200 dark:hover:bg-white/5', 'hover:bg-white/5'
    $c = $c -replace 'hover:bg-slate-200 dark:hover:bg-white/\[0\.04\]', 'hover:bg-white/[0.04]'
    $c = $c -replace 'hover:text-slate-800 dark:hover:text-white/80', 'hover:text-white/80'
    $c = $c -replace 'hover:text-slate-900 dark:hover:text-white"', 'hover:text-white"'
    $c = $c -replace 'hover:border-slate-300 dark:hover:border-white/10', 'hover:border-white/10'
    $c = $c -replace 'hover:border-slate-400 dark:hover:border-white/20', 'hover:border-white/20'
    $c = $c -replace 'bg-slate-200 dark:bg-black', 'bg-black'
    $c = $c -replace 'group-hover:text-slate-900 dark:group-hover:text-white', 'group-hover:text-white'
    $c = $c -replace 'text-slate-900 dark:text-text-main', 'text-text-main'
    $c = $c -replace 'shadow-\[0_0_20px_rgba\(0,0,0,0\.1\)\] dark:shadow-none ', ''
    $c = $c -replace 'bg-white/80 dark:bg-black/50', 'bg-black/50'
    $c = $c -replace 'border border-slate-200/50 dark:border-white/10', 'border border-white/10'
    
    Set-Content $_.FullName $c
}
